#server:
#  port: 8110 # 服务端口
#  tomcat:
#    max-threads: 10 # tomcat的最大并发值修改为10,默认是200
#
#spring:
#  profiles:
#    active: dev # 环境设置（开发环境）
#  application:
#    name: service-edu # 服务名（微服务会用到，名字里不要包含下划线，注册的时候容易出问题）
#  datasource: # mysql数据库连接
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
#    username: 用户名
#    password: 密码
#  # 默认情况下json时间格式带有时区，并且是世界标准时间，和我们的时间差了八个小时，所以得改回来
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  # nacos配置:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 # nacos服务地址
#    # sentinel 服务容错配置
#    sentinel:
#      transport:
#        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
#        dashboard: localhost:8080 # 指定控制台服务的地址
#  redis:
#    host: 192.168.174.5
#    port: 6379
#    database: 0
#    password: 123456 #默认为空
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
#
## SQL执行语句打印日志
#mybatis-plus:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/zs/guli/service/edu/mapper/xml/*.xml
#
## 设置日志级别，默认日志框架为Logback
## 注意：Logback是log4j框架的作者开发的新一代日志框架，它效率更高、能够适应诸多的运行环境，同时天然支持SLF4J。
#logging:
#  level:
#    root: info
#
#
## 负载均衡规则
##service-oss: # 调用的提供者的名称
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#
#ribbon:
#  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
#  ConnectTimeout: 50000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 50000 #处理请求的超时时间，默认为1秒
#
#feign:
#  sentinel:
#    enabled: true
